spring:
  liquibase:
    enabled: true
    change-log: classpath*:db/changelog/db.changelog-master.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    serialization:
      fail-on-empty-beans: false
jwt:
  token:
    secret: HighLoad1